import builtins from 'builtin-modules';
import { defineConfig } from 'tsup';

const prod = process.argv[2] === 'production';
const test_build = process.argv[2] === 'test' || process.argv[3] === 'test';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY TSUP
if you want to view the source, please visit the github repository of this plugin
*/
`;

export default defineConfig({
  banner: {
    js: banner,
  },
  bundle: true,
  entry: ['src/main.ts'],
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/closebrackets',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/comment',
    '@codemirror/fold',
    '@codemirror/gutter',
    '@codemirror/highlight',
    '@codemirror/history',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/matchbrackets',
    '@codemirror/panel',
    '@codemirror/rangeset',
    '@codemirror/rectangular-selection',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/stream-parser',
    '@codemirror/text',
    '@codemirror/tooltip',
    '@codemirror/view',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2020',
  outDir: 'dist',
  sourcemap: prod ? false : 'inline',
  clean: true,
  minify: prod,
  dts: true,
  platform: 'neutral',
});
